# ==========================
# Loon rule policy
# ==========================


# 广告
ads=REJECT
trackerslist=REJECT


# 直连
cn=DIRECT
cn_lite=DIRECT
private=DIRECT

microsoft_cn=DIRECT
apple_cn=DIRECT
google_cn=DIRECT

games_cn=DIRECT


# 代理
gfw=PROXY
proxy=PROXY

youtube=PROXY
tiktok=PROXY

netflix=PROXY
disney=PROXY
max=PROXY
primevideo=PROXY
appletv=PROXY

games=PROXY

ai=PROXY
media=PROXY
spotify=PROXY