# ==========================
# Loon rule policy
# ==========================


# ==========================
# 广告 / 跟踪
# ==========================

ads=REJECT
trackerslist=REJECT



# ==========================
# 直连
# ==========================

cn=DIRECT
cn_lite=DIRECT

private=DIRECT
privateip=DIRECT

cnip=DIRECT


# 国内服务

microsoft_cn=DIRECT
apple_cn=DIRECT
google_cn=DIRECT

games_cn=DIRECT

bilibili=DIRECT

networktest=DIRECT



# ==========================
# 代理
# ==========================

gfw=PROXY
proxy=PROXY


# 视频媒体

youtube=PROXY
netflix=PROXY
disney=PROXY
max=PROXY
primevideo=PROXY
appletv=PROXY


# 社交 / 娱乐

tiktok=PROXY
spotify=PROXY

media=PROXY


# 游戏

games=PROXY


# AI

ai=PROXY


# IP 媒体

telegramip=PROXY

netflixip=PROXY

mediaip=PROXY



# ==========================
# 特殊
# ==========================

tld_proxy=PROXY