name: Build ruleset and geodata

on:

  workflow_dispatch:

  schedule:
  - cron: "0 19 * * *"

  push:
    branches:
    - main

    paths-ignore:
    - "**/README.md"
    - "**/*.ini"

permissions:

  contents: write
  actions: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # ============================================================
    # Set variables
    # ============================================================

    - name: Set variables

      run: |
        
        echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}


        echo "singbox_core_release_version=$(curl -sSL https://api.github.com/repos/reF1nd/sing-box/tags?per_page=100 \
        | jq -r '.[].name' \
        | grep -P '^v?[0-9]+\.[0-9]+\.[0-9]+-reF1nd.*' \
        | head -n 1 \
        | awk -F'[v.-]' '{print $2"."$3".0"}')" >> ${GITHUB_ENV}


        echo "singbox_core_latest_version=$(curl -sSL \
        https://raw.githubusercontent.com/reF1nd/sing-box/reF1nd-testing/docs/configuration/rule-set/source-format.md \
        | awk '/\*/ {last=$0} END {print last}' \
        | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')" >> ${GITHUB_ENV}


        echo "singbox_core_compatible_version=$(curl -sSL \
        https://raw.githubusercontent.com/reF1nd/sing-box/reF1nd-testing/docs/configuration/rule-set/source-format.md \
        | awk '/\*/{lines[++count]=$0} END{print lines[count-1]}' \
        | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')" >> ${GITHUB_ENV}


        echo "singbox_rules_latest_version=$(curl -sSL \
        https://raw.githubusercontent.com/reF1nd/sing-box/reF1nd-testing/docs/configuration/rule-set/source-format.md \
        | awk '/\*/ {last=$0} END {print last}' \
        | sed -n 's/^* \([0-9]\+\):.*/\1/p')" >> ${GITHUB_ENV}


        echo "singbox_rules_compatible_version=$(curl -sSL \
        https://raw.githubusercontent.com/reF1nd/sing-box/reF1nd-testing/docs/configuration/rule-set/source-format.md \
        | awk '/\*/{lines[++count]=$0} END{print lines[count-1]}' \
        | sed -n 's/^* \([0-9]\+\):.*/\1/p')" >> ${GITHUB_ENV}


        echo "domains_download_url=https://github.com/DustinWin/domain-list-custom/releases/download/domains" >> ${GITHUB_ENV}


        echo "ips_download_url=https://github.com/DustinWin/geoip/releases/download/ips" >> ${GITHUB_ENV}

      shell: bash

    # ============================================================
    # Checkout
    # ============================================================


    - name: Clone Repository

      uses: actions/checkout@v7

    - name: Checkout `DustinWin/domain-list-custom`

      uses: actions/checkout@v7

      with:

        repository: DustinWin/domain-list-custom

        path: custom

    - name: Checkout `v2fly/domain-list-community`

      uses: actions/checkout@v7

      with:

        repository: v2fly/domain-list-community

        path: community

    # ============================================================
    # Go
    # ============================================================


    - name: Setup Go

      uses: actions/setup-go@v7

      with:

        go-version-file: ./custom/go.mod

        cache-dependency-path: ./custom/go.sum

    # ============================================================
    # Generate mihomo geodata
    # ============================================================

    - name: Generate `mihomo` geodata

      run: |
        
        mkdir -p ./tmp/ ./community/mydata/


        archs1=(ads private trackerslist microsoft-cn apple-cn google-cn games-cn games netflix disney max primevideo appletv youtube tiktok bilibili spotify media ai networktest tld-proxy gfw proxy cn)


        archs2=(ads private microsoft-cn apple-cn google-cn games-cn games ai networktest tld-proxy gfw proxy cn)


        archs3=(private microsoft-cn apple-cn google-cn games-cn gfw cn-lite)


        curl -sSL "${domains_download_url}/fakeip-filter.list" \
        | awk '!/(DOMAIN-REGEX,|ntp|stun|time)/' \
        | sed \
        -e 's/DOMAIN,/full:/' \
        -e 's/DOMAIN-SUFFIX,//' \
        > ./tmp/temp-fakeip-filter.txt


        cat <<EOF >> ./tmp/temp-fakeip-filter.txt
          keyword:ntp
          keyword:stun
          keyword:time
        EOF


        curl -sSL "${domains_download_url}/fakeip-filter.list" \
        | awk '/DOMAIN-REGEX,/ && !/(ntp|stun|time)/' \
        | sed 's/DOMAIN-REGEX,/regexp:/' \
        >> ./tmp/temp-fakeip-filter.txt


        sort --ignore-case ./tmp/temp-fakeip-filter.txt \
        > ./tmp/fakeip-filter.txt


        cd ./community/


        for arch1 in "${archs1[@]}"; do

          curl -sSL \
          "${domains_download_url}/${arch1}.list" \
          | sed \
          -e 's/DOMAIN,/full:/' \
          -e 's/DOMAIN-SUFFIX,//' \
          -e 's/DOMAIN-KEYWORD,/keyword:/' \
          -e 's/DOMAIN-REGEX,/regexp:/' \
          > "./mydata/${arch1}"

        done


        cp ../tmp/fakeip-filter.txt ./mydata/fakeip-filter


        go run ./ \
        --datapath=./mydata/ \
        --outputname geosite-all.dat


        rm -f ./mydata/ads


        go run ./ \
        --datapath=./mydata/ \
        --outputname geosite-all-lite.dat
    # ============================================================
    # Get geoip files
    # ============================================================

    - name: Get geoip relative files

      run: |
        
        mkdir -p ./mihomo-geodata/


        mihomo_mmdb=($(curl -sSL \
        https://api.github.com/repos/DustinWin/geoip/releases \
        | awk '/"browser_download_url"/' \
        | awk '/.mmdb/' \
        | awk -F '"' '{print $4}'))


        count_mihomo_mmdb=${#mihomo_mmdb[@]}


        for ((i = 0; i < count_mihomo_mmdb; i++)); do

          wget -q \
          -P ./mihomo-geodata/ \
          "${mihomo_mmdb[i]}"

        done



        mihomo_others=($(curl -sSL \
        https://api.github.com/repos/DustinWin/geoip/releases \
        | awk '/"browser_download_url"/' \
        | awk '/\/mihomo-geodata\//' \
        | awk '!/\.mmdb/' \
        | awk -F '"' '{print $4}'))


        count_mihomo_others=${#mihomo_others[@]}


        for ((i = 0; i < count_mihomo_others; i++)); do

          wget -q \
          -P ./community/ \
          "${mihomo_others[i]}"

        done

    # ============================================================
    # Download mihomo ruleset source
    # ============================================================

    - name: Download `mihomo` rule-set files

      run: |
        
        mkdir -p ./mihomo-ruleset/


        domains=(ads trackerslist microsoft-cn apple-cn google-cn games-cn games netflix disney max primevideo appletv youtube tiktok bilibili spotify media ai networktest tld-proxy gfw proxy cn cn-lite)


        ips=(privateip cnip telegramip netflixip mediaip)



        for domain in "${domains[@]}"; do


          mkdir -p \
          "./tools/domains/${domain}/"



          curl -sSL \
          "${domains_download_url}/${domain}.list" \
          | awk '/(DOMAIN,|DOMAIN-SUFFIX,)/' \
          | sed \
          -e 's/DOMAIN,//' \
          -e 's/DOMAIN-SUFFIX,/\+\./' \
          > "./tools/domains/${domain}/${domain}.list"


        done




        for ip in "${ips[@]}"; do


          mkdir -p \
          "./tools/ips/${ip}/"



          curl -sSL \
          "${ips_download_url}/${ip}.list" \
          | sed 's/.*,//' \
          > "./tools/ips/${ip}/${ip}.list"


        done

    # ============================================================
    # Generate mihomo mrs
    # ============================================================

    - name: Generate `mihomo` rule-set (mrs) and move .list files

      run: |
        

        curl -sS \
        -o ./tools/mihomo \
        -L https://github.com/DustinWin/proxy-tools/releases/download/mihomo/mihomo-meta-linux-amd64-v3.upx


        chmod +x ./tools/mihomo



        cd ./tools/



        list=($(ls ./domains/))


        for ((i = 0; i < ${#list[@]}; i++)); do


          ./mihomo convert-ruleset \
          domain text \
          "./domains/${list[i]}/${list[i]}.list" \
          "../mihomo-ruleset/${list[i]}.mrs"



          mv -f \
          "./domains/${list[i]}/${list[i]}.list" \
          "../mihomo-ruleset/"


        done




        list=($(ls ./ips/))


        for ((i = 0; i < ${#list[@]}; i++)); do


          ./mihomo convert-ruleset \
          ipcidr text \
          "./ips/${list[i]}/${list[i]}.list" \
          "../mihomo-ruleset/${list[i]}.mrs"



          mv -f \
          "./ips/${list[i]}/${list[i]}.list" \
          "../mihomo-ruleset/"


        done



        rm -rf \
        ./mihomo \
        ./domains \
        ./ips
    # ============================================================
    # Move mihomo geodata files
    # ============================================================

    - name: Move `mihomo` geodata files

      run: |
        
        cd ./community/ || exit 1


        for file in $(ls *.dat *.metadb); do

          install -Dp \
          "./${file}" \
          ../mihomo-geodata/

        done


        rm -rf ../custom* ../community*

    # ============================================================
    # Download sing-box rule_set files
    # ============================================================

    - name: Download `sing-box` rule_set files

      run: |
        
        domains=(ads private trackerslist microsoft-cn apple-cn google-cn games-cn games netflix disney max primevideo appletv youtube tiktok bilibili spotify media ai networktest tld-proxy gfw proxy cn cn-lite)

        ips=(privateip cnip telegramip netflixip mediaip)



        for domain in "${domains[@]}"; do


          mkdir -p \
          "./tools/rules/${domain}/"



          curl -sSL \
          "${domains_download_url}/${domain}.list" \
          > "./tools/rules/${domain}/${domain}.list"


        done




        for ip in "${ips[@]}"; do


          mkdir -p \
          "./tools/rules/${ip}/"



          curl -sSL \
          "${ips_download_url}/${ip}.list" \
          > "./tools/rules/${ip}/${ip}.list"


        done




        mkdir -p ./tools/rules/fakeip-filter/


        curl -sSL \
        "${domains_download_url}/fakeip-filter.list" \
        > ./tools/rules/fakeip-filter/fakeip-filter.list




        mkdir -p ./tools/rules/applications/


        curl -sSL \
        "${domains_download_url}/applications.list" \
        > ./tools/rules/applications/applications.list

    # ============================================================
    # Generate sing-box rule_set
    # ============================================================

    - name: Generate `sing-box` rule_set files

      run: |
        
        if [[ "${{ env.singbox_core_latest_version }}" == "${{ env.singbox_core_release_version }}" ]]; then



          echo "singbox_equal=true" >> $GITHUB_ENV



          curl -sS \
          -L \
          "https://github.com/SagerNet/sing-box/releases/download/v${{ env.singbox_core_compatible_version }}/sing-box-${{ env.singbox_core_compatible_version }}-linux-amd64.tar.gz" \
          | tar -zx -C ./tools/



          mv \
          "./tools/sing-box-${{ env.singbox_core_compatible_version }}-linux-amd64/sing-box" \
          ./tools/sing-box



          mkdir -p ./sing-box-ruleset-compatible/



          cd ./tools/



          sed -i \
          's/"version": 1/"version": ${{ env.singbox_rules_compatible_version }}/' \
          ./convert.sh



          chmod +x ./convert.sh


          ./convert.sh



          mv -f \
          ./*.json \
          ./*.srs \
          ../sing-box-ruleset-compatible/



          rm -rf ./sing-box*




          cd ../



          curl -sS \
          -o ./tools/sing-box \
          -L \
          https://github.com/DustinWin/proxy-tools/releases/download/sing-box/sing-box-ref1nd-stable-linux-amd64-v3.upx



          chmod +x ./tools/sing-box



          mkdir -p ./sing-box-ruleset/



          cd ./tools/



          sed -i \
          's/"version": ${{ env.singbox_rules_compatible_version }}/"version": ${{ env.singbox_rules_latest_version }}/' \
          ./convert.sh



          ./convert.sh



          mv -f \
          ./*.json \
          ./*.srs \
          ../sing-box-ruleset/



          rm -rf ./sing-box* ./rules*



        else



          echo "singbox_equal=false" >> $GITHUB_ENV



          curl -sS \
          -o ./tools/sing-box \
          -L \
          https://github.com/DustinWin/proxy-tools/releases/download/sing-box/sing-box-ref1nd-stable-linux-amd64-v3.upx



          chmod +x ./tools/sing-box



          mkdir -p ./sing-box-ruleset-compatible/



          cd ./tools/



          sed -i \
          's/"version": 1/"version": ${{ env.singbox_rules_compatible_version }}/' \
          ./convert.sh



          ./convert.sh



          mv -f \
          ./*.json \
          ./*.srs \
          ../sing-box-ruleset-compatible/



          rm -rf ./sing-box*



          cd ../



          curl -sS \
          -o ./tools/sing-box \
          -L \
          https://github.com/DustinWin/proxy-tools/releases/download/sing-box/sing-box-ref1nd-testing-linux-amd64-v3.upx



          chmod +x ./tools/sing-box



          mkdir -p ./sing-box-ruleset/



          cd ./tools/



          sed -i \
          's/"version": ${{ env.singbox_rules_compatible_version }}/"version": ${{ env.singbox_rules_latest_version }}/' \
          ./convert.sh



          ./convert.sh



          mv -f \
          ./*.json \
          ./*.srs \
          ../sing-box-ruleset/



          rm -rf ./sing-box* ./rules*



        fi
    # ============================================================
    # Release sing-box compatible ruleset
    # ============================================================

    - name: Release and upload `sing-box-ruleset-compatible` assets

      uses: svenstaro/upload-release-action@v2

      with:

        repo_token: ${{ secrets.GITHUB_TOKEN }}

        release_name: sing-box-ruleset-compatible

        tag: sing-box-ruleset-compatible

        overwrite: true

        body: |
          
          sing-box rule_set 兼容规则

          适用于：
          v${{ env.singbox_core_old_version }}
          -
          v${{ env.singbox_core_new_version }}
          （不包含）

          ruleset:
          ${{ env.singbox_ruleset_old_version }}

          更新于：
          ${{ env.update_version }}

        file_glob: true

        file: ./sing-box-ruleset-compatible/*

    # ============================================================
    # Release sing-box ruleset
    # ============================================================


    - name: Release and upload `sing-box-ruleset` assets

      if: ${{ env.singbox_equal == 'true' }}

      uses: svenstaro/upload-release-action@v2

      with:

        repo_token: ${{ secrets.GITHUB_TOKEN }}

        release_name: sing-box-ruleset

        tag: sing-box-ruleset

        overwrite: true

        body: |
          
          sing-box rule_set 文件

          适用于：
          v${{ env.singbox_core_new_version }}
          +

          ruleset:
          ${{ env.singbox_ruleset_new_version }}

          更新于：
          ${{ env.update_version }}

        file_glob: true

        file: ./sing-box-ruleset/*

    - name: Release and upload `sing-box-ruleset` assets

      if: ${{ env.singbox_equal == 'false' }}

      uses: svenstaro/upload-release-action@v2

      with:

        repo_token: ${{ secrets.GITHUB_TOKEN }}

        release_name: sing-box-ruleset

        tag: sing-box-ruleset

        overwrite: true

        body: |
          
          sing-box rule_set 文件

          适用于：
          v${{ env.singbox_core_new_version }}

          ruleset:
          ${{ env.singbox_ruleset_new_version }}

          更新于：
          ${{ env.update_version }}

        file_glob: true

        file: ./sing-box-ruleset/*
    # ============================================================
    # Purge jsDelivr CDN
    # ============================================================


    - name: Purge jsDelivr CDN

      run: |
        

        # ------------------------------
        # mihomo-geodata
        # ------------------------------

        cd ./mihomo-geodata/ || exit 1


        for file in $(ls); do

          curl -i \
          "https://purge.jsdelivr.net/gh/${{ github.repository }}@mihomo-geodata/${file}"

        done




        # ------------------------------
        # mihomo-ruleset
        # ------------------------------

        cd ../mihomo-ruleset/ || exit 1


        for file in $(ls); do

          curl -i \
          "https://purge.jsdelivr.net/gh/${{ github.repository }}@mihomo-ruleset/${file}"

        done





        # ------------------------------
        # loon-ruleset
        # ------------------------------

        cd ../loon-ruleset/ || exit 1


        for file in $(ls); do

          curl -i \
          "https://purge.jsdelivr.net/gh/${{ github.repository }}@loon-ruleset/${file}"

        done





        # ------------------------------
        # sing-box-ruleset-compatible
        # ------------------------------

        cd ../sing-box-ruleset-compatible/ || exit 1


        for file in $(ls); do

          curl -i \
          "https://purge.jsdelivr.net/gh/${{ github.repository }}@sing-box-ruleset-compatible/${file}"

        done





        # ------------------------------
        # sing-box-ruleset
        # ------------------------------

        cd ../sing-box-ruleset/ || exit 1


        for file in $(ls); do

          curl -i \
          "https://purge.jsdelivr.net/gh/${{ github.repository }}@sing-box-ruleset/${file}"

        done

    # ============================================================
    # Delete old workflow runs
    # ============================================================


    - name: Delete old workflow runs

      uses: Mattraks/delete-workflow-runs@v2

      with:

        token: ${{ secrets.GITHUB_TOKEN }}

        repository: ${{ github.repository }}

        retain_days: 3

        keep_minimum_runs: 1
